stages:
  ingest_data:
    cmd: python pipelines/data_ingestion/ingest_raw_data.py
    deps:
      - pipelines/data_ingestion/ingest_raw_data.py
    params:
      - pipelines/config/pipeline_config.yaml:data_source
    outs:
      - data/raw

  data_validation:
    cmd: python pipelines/data_ingestion/data_validation.py
    deps:
      - data/raw
    outs:
      - data/validated

  preprocess_data:
    cmd: python pipelines/data_ingestion/data_preprocessing.py
    deps:
      - data/validated
    outs:
      - data/processed

  feature_engineering:
    cmd: python pipelines/feature_engineering/feature_transformations.py
    deps:
      - data/processed
    params:
      - pipelines/config/feature_config.yaml:transformations
      - pipelines/config/feature_config.yaml:selected_features
    outs:
      - data/features

  hyperparameter_tuning:
    cmd: python pipelines/model_training/hyperparameter_tuning.py
    deps:
      - data/features
    params:
      - pipelines/config/hyperparams.yaml:model
      - pipelines/config/hyperparams.yaml:grid_search
    outs:
      - data/models/tuning/tuned_model.pkl  # Separate directory for tuned model

  train_model:
    cmd: python pipelines/model_training/train_model.py
    deps:
      - data/models/tuning/tuned_model.pkl
      - data/features
    params:
      - pipelines/config/model_config.yaml:model_type
      - pipelines/config/model_config.yaml:layers
      - pipelines/config/model_config.yaml:optimizer
      - pipelines/config/model_config.yaml:loss_function
    outs:
      - data/models/final/latest_model.pkl  # Separate directory for final model

  evaluate_model:
    cmd: python pipelines/model_evaluation/evaluate_model.py
    deps:
      - data/models/final/latest_model.pkl
      - data/test
    metrics:
      - metrics/evaluate_metrics.json  # Unique metrics file for evaluation

  interpretability_analysis:
    cmd: python pipelines/interpretability_pipeline.py
    deps:
      - data/models/final/latest_model.pkl
      - data/test
    params:
      - pipelines/config/monitoring_config.yaml:metrics_to_monitor
    outs:
      - results/interpretability  # Directory for interpretability results

  adversarial_testing:
    cmd: python pipelines/adversarial_testing.py
    deps:
      - data/models/final/latest_model.pkl
      - data/adversarial_samples
    params:
      - pipelines/config/monitoring_config.yaml:drift_threshold
      - pipelines/config/monitoring_config.yaml:alert_channel
    metrics:
      - metrics/adversarial_metrics.json  # Unique metrics file for adversarial testing

  model_registry:
    cmd: python pipelines/model_serving/register_model.py
    deps:
      - data/models/final/latest_model.pkl
    params:
      - pipelines/config/registry_config.yaml:registry
      - pipelines/config/registry_config.yaml:metadata
    outs:
      - data/models/registry/best_model_v1.pkl  # Directory for model registry
